name: ci/cd

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_and_test_dev:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: build 
        run: docker compose up --build -d
      -
        name: test
        run: docker compose run --rm test

  promote_to_main_and_deploy:
    runs-on: ubuntu-latest
    needs: build_and_test_dev
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Merge dev into main
        run: 
          git config user.name "vidyazetexa"
          git config user.email "vidya.bhushan@zetexa.com"
          git checkout main
          git merge dev --no-ff --no-edit
          git push origin main
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push final image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
