name: ECR Image Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: 073042140176
  ECR_REPOSITORY: 073042140176.dkr.ecr.ap-south-1.amazonaws.com


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Log in to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      # - name: Build Docker image
      #   run: |
      #     docker compose -f docker-compose.yaml build

          
      # - name: Push Docker image to Amazon ECR
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install dos2unix
      #     dos2unix ./pushImages/push_images.sh
      #     ./pushImages/push_images.sh


